env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - RELEASE_BUILDS=dist/escapepod_darwin_amd64/escapepod dist/escapepod_linux_amd64/escapepod dist/escapepod_windows_amd64/escapepod.exe

before:
  hooks:
    - make build-frontend

builds:
  - binary: escapepod
    main: ./cmd/escapepod
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    hooks:
      post: make pack-releases

archives:
  - format: tar.gz

archive:
  wrap_in_directory: true
  name_template: "{{ .ProjectName  }}-{{ .Tag  }}-{{ .Os  }}-{{ .Arch  }}"

checksum:
  name_template: "SHA256SUMS"

dockers:
  - goos: linux
    goarch: amd64
    binaries:
      - escapepod
    image_templates:
      - "rphillips/escapepod:latest"
      - "rphillips/escapepod:{{ .Tag }}"
    dockerfile: Dockerfile
    extra_files:
      - escapepod.toml.sample
